version: '2'
services:
  app:
    build: .
    command: npm start
    container_name: 'app'
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '3600:3600'
    depends_on:
      - localdb
    links:
      - localdb
    environment:
      EXPRESS_PORT: 8080
      MONGODB_HOST: localdb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: rest-learning
      # MONGODB_AUTH_DATABASE: admin

  localdb:
    image: mongo:latest
    container_name: 'localdb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    expose:
      - '27017'
    ports:
      - 27018:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet